In [8]:
from tensorflow.keras.preprocessing.text import one_hot

In [9]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [10]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [11]:
## Define the vocabulary size
voc_size=10000

In [12]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [13]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5878, 2807, 8572, 1940],
 [5878, 2807, 8572, 6485],
 [5878, 4480, 8572, 4479],
 [6309, 4899, 9100, 3089, 2870],
 [6309, 4899, 9100, 3089, 1352],
 [8622, 5878, 5247, 8572, 6473],
 [793, 7965, 8680, 3089]]

In [14]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [15]:
import numpy as np

In [16]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5878 2807 8572 1940]
 [   0    0    0    0 5878 2807 8572 6485]
 [   0    0    0    0 5878 4480 8572 4479]
 [   0    0    0 6309 4899 9100 3089 2870]
 [   0    0    0 6309 4899 9100 3089 1352]
 [   0    0    0 8622 5878 5247 8572 6473]
 [   0    0    0    0  793 7965 8680 3089]]


In [17]:
## feature representation
dim=10

In [18]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 89ms/step


array([[[ 0.03502622, -0.01036898,  0.02225803,  0.03198966,
         -0.0258401 , -0.00110582,  0.00487977,  0.00164454,
          0.01469144, -0.03680389],
        [ 0.03502622, -0.01036898,  0.02225803,  0.03198966,
         -0.0258401 , -0.00110582,  0.00487977,  0.00164454,
          0.01469144, -0.03680389],
        [ 0.03502622, -0.01036898,  0.02225803,  0.03198966,
         -0.0258401 , -0.00110582,  0.00487977,  0.00164454,
          0.01469144, -0.03680389],
        [ 0.03502622, -0.01036898,  0.02225803,  0.03198966,
         -0.0258401 , -0.00110582,  0.00487977,  0.00164454,
          0.01469144, -0.03680389],
        [ 0.00623149,  0.03398556,  0.0360061 , -0.01199447,
         -0.00453272, -0.04981579,  0.01496578, -0.00300348,
         -0.04335986, -0.02506499],
        [ 0.02751421,  0.04270084, -0.02266667,  0.00981451,
          0.04856132,  0.00875013,  0.0042285 ,  0.00273367,
         -0.01552694,  0.00826757],
        [ 0.04935395, -0.01257317, -0.00424528,  0.0

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 5878, 2807, 8572, 1940], dtype=int32)

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 42ms/step


array([[ 0.03502622, -0.01036898,  0.02225803,  0.03198966, -0.0258401 ,
        -0.00110582,  0.00487977,  0.00164454,  0.01469144, -0.03680389],
       [ 0.03502622, -0.01036898,  0.02225803,  0.03198966, -0.0258401 ,
        -0.00110582,  0.00487977,  0.00164454,  0.01469144, -0.03680389],
       [ 0.03502622, -0.01036898,  0.02225803,  0.03198966, -0.0258401 ,
        -0.00110582,  0.00487977,  0.00164454,  0.01469144, -0.03680389],
       [ 0.03502622, -0.01036898,  0.02225803,  0.03198966, -0.0258401 ,
        -0.00110582,  0.00487977,  0.00164454,  0.01469144, -0.03680389],
       [ 0.00623149,  0.03398556,  0.0360061 , -0.01199447, -0.00453272,
        -0.04981579,  0.01496578, -0.00300348, -0.04335986, -0.02506499],
       [ 0.02751421,  0.04270084, -0.02266667,  0.00981451,  0.04856132,
         0.00875013,  0.0042285 ,  0.00273367, -0.01552694,  0.00826757],
       [ 0.04935395, -0.01257317, -0.00424528,  0.04424766,  0.00939932,
         0.03072702, -0.01725265,  0.03190012